version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo_new
  mongo_new:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"